# Generated by Django 5.2.13 on 2026-04-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_livro_capa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
    ]
